# Generated by Django 4.1.12 on 2023-10-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=60)),
                ('loaction', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
