# Generated by Django 4.1.12 on 2023-10-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_remove_job_jobname_job_company_job_positionname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='10000', max_length=60),
        ),
    ]
